config/routes.rb
Rails.application.routes.draw do
  # get 'relationships/create'
  # get 'relationships/destroy'
  get 'favorites/create'
  get 'favorites/destroy'
  root 'homes#top'
  get '/home/about' => 'homes#about'
  get '/home' => 'homes#top'

  devise_for :users

  resources :books do
    resource :favorites, only:[:create, :destroy]
    resources :post_comments, only:[:create, :destroy]
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :searches,only:[:index]
  # searchesのindexを表示させる為に書いている

end

app/models/user.rb
class User < ApplicationRecord

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable,:validatable

  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :post_comments, dependent: :destroy
  has_many :active_relationships, class_name: "Relationship", foreign_key: :following_id
  has_many :followings, through: :active_relationships, source: :follower
  has_many :passive_relationships, class_name: "Relationship", foreign_key: :follower_id
  has_many :followers, through: :passive_relationships, source: :following
  attachment :profile_image, destroy: false

  def followed_by?(user)
       passive_relationships.find_by(following_id: user.id).present?
  end

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction,
     length: { maximum: 50, message: 'is too long (maximum is 50 characters)' }

     def self.search(search)
          if search
               User.where(['name LIKE ?', "%#{search}%"])
               else
               User.all
               end
          end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!
	before_action :baria_user, only: [:update, :edit]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
	  @book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）

  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す
    @book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
    @user = current_user
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
	  if @user.update(user_params)
		redirect_to user_path(@user), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  def follows
    user = User.find(params[:id])
    @users = user.followings
  end

  def followers
    user = User.find(params[:id])
    @users = user.followers
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
   def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
   end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
		<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

		<tr>
			<th>name</th>
			<th><%= user.name %></th>
		</tr>

		<tr>
			<th>introduction</th>
			<th><%= user.introduction %></th>
		</tr>

		<tr>
		<th>follow</th>
			<th><%= link_to user.active_relationships.count, follows_user_path(user.id) %></th>
		</tr>

		<tr>
		<th>follower</th>
		<th><%=link_to user.passive_relationships.count, followers_user_path(user.id) %></th>
		</tr>
		<tr>
		<% if current_user != user %>
			<% if user.followed_by?(current_user) %>
				<th><%=link_to "フォローを外す", user_relationships_path(user.id), method: :delete, class: "btn btn-info col-xs-12 col-xs-offset-1" %></th>
			<% else %>
				<th><%=link_to "フォローする", user_relationships_path(user.id), method: :post, class: "btn btn-success col-xs-12 col-xs-offset-1" %></th>
			<% end %>
		<% end %>
		</tr>

</table>

<div class="row">
<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>
</div>

app/views/users/edit.html.erb
<h2>User info</h2>


<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<%= form_for(@user) do |f| %>
<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/followers.html.erb
<div class = container>
<div class = row>
<div class="col-xs-9">
    <h2>Follower Users</h2>
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="3"></th>
				</tr>
			</thead>
		<!--follow一覧 -->
    <tbody>
    <% @users.each do |user| %>
            <tr>
                <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
                <td><%= user.name%></td>
                <td>フォロー数：<%= user.active_relationships.count %></td>
                <td>フォローワー数：<%= user.passive_relationships.count %></td>
        <% if current_user != user %>
            <% if user.followed_by?(current_user) %>
                <td><%=link_to "フォローを外す", user_relationships_path(user.id), method: :delete %></td>
            <% else %>
                <td><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
            <% end %>
        <% end %>
                <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
            </tr>
        </div>
    <% end %>
</table>
    </tbody>
    </div>
    </div>

app/views/users/follows.html.erb
<div class = container>
<div class = row>
<div class="col-xs-9">
    <h2>Follow Users</h2>
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="4"></th>
				</tr>
			</thead>
		<!--follow一覧 -->
    <tbody>
    <% @users.each do |user| %>
            <tr>
                <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
                <td><%= user.name%></td>
                <td>フォロー数：<%= user.active_relationships.count %></td>
                <td>フォローワー数：<%= user.passive_relationships.count %></td>
        <% if current_user != user %>
            <% if user.followed_by?(current_user) %>
                <td><%=link_to "フォローを外す", user_relationships_path(user.id), method: :delete %></td>
            <% else %>
                <td><%=link_to "フォローする", user_relationships_path(user.id), method: :post %></td>
            <% end %>
        <% end %>
                <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
            </tr>
        </div>
    <% end %>
</table>
    </tbody>
    </div>
    </div>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-3">
		<h2>User info</h2>
		  <%= render 'users/profile', user: current_user %>
				<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない.元々はcurrent_userになっていた -->
		<h2>New book</h2>
		  <%= render 'books/newform', book: @book %>
	</div>
		  <div class="col-xs-9">
			<h2>Users</h2>
			<!--users一覧 -->
			<table class="table">
				<thead>
					<tr>
						<th>image</th>
						<th>name</th>
						<th colspan="4"></th>
					</tr>
				</thead>
				<tbody>
						<% @users.each do |user| %>
					<tr>
						<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
						<td><%= user.name%></td>
						<td>フォロー数：<%= user.active_relationships.count %></td>
						<td>フォローワー数：<%= user.passive_relationships.count %></td>
							<% if current_user != user %>
								<% if user.followed_by?(current_user) %>
									<td><%=link_to "フォローを外す", user_relationships_path(user.id), method: :delete %></td>
								<% else %>
									<td><%=link_to "フォローする", user_relationships_path(user.id), method: :book %></td>
								<% end %>
							<% end %>
						<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
						<% end %>
					</tr>
				</tbody>
			</table>
<!--users一覧 -->
        </div>
    </div>

app/views/users/show.html.erb
<div class="container">
	<div class="row">
		<div class="col-xs-3">
			<h2>User info</h2>
			<%= render 'users/profile', user: @user %>
	<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない.元々はcurrent_userになっていた -->
			<h2>New book</h2>
			<%= render 'books/newform', book: @book %>
	<!--同コントローラーのviewで表示ならusersは省略可 -->
		</div>
<div class="col-xs-9">
<h2>Books</h2>
<!--books一覧 -->
<table class="table table-hover table-inverse">
	<thead>
		<tr>
			<th></th>
			<th>Title</th>
			<th>Opinion</th>
			<th colspan="3"></th>
		</tr>
	</thead>

	<tbody>
		<% @books.each do |book| %>
		<tr>
			<td>
				<%= link_to (book.user) do %>
				<%= attachment_image_tag book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg" %>
				<% end %>
			</td>
			<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
			<td><%= book.body %></td>
		<% if user_signed_in? %>
			<% if @book.post_commented_by?(current_user) %> <!-- ログインしているユーザーがコメントしたかどうかで分岐 -->
					<td><span>コメント数: </span><%=book.post_comments.count %></td>
				<% else %>
					<td><span>コメント数: </span><%=book.post_comments.count %></td>
				<% end %>
				<% else %>
					<td><span>コメント数: </span><%= book.post_comments.count %></td>
			<% end %>
		<% end %>
		</tr>
	</tbody>
</table>
<!--books一覧 -->
	</div>
</div>
</div>