config/routes.rb
Rails.application.routes.draw do
  # get 'relationships/create'
  # get 'relationships/destroy'
  get 'favorites/create'
  get 'favorites/destroy'
  root 'homes#top'
  get '/home/about' => 'homes#about'
  get '/home' => 'homes#top'

  devise_for :users

  resources :books do
    resource :favorites, only:[:create, :destroy]
    resources :post_comments, only:[:create, :destroy]
  end
  resources :users do
    resource :relationships, only: [:create, :destroy]
    get :follows, on: :member
    get :followers, on: :member
  end
  resources :searches,only:[:index]
  # searchesのindexを表示させる為に書いている

end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites
	has_many :post_comments

	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	def post_commented_by?(user)
        post_comments.where(user_id: user.id).exists?
	end

	def self.search(search)
		if search
			Book.where(['title LIKE ?', "%#{search}%"])
		  else
			Book.all
		  end
	  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	before_action :authenticate_user!
	before_action :correct_user, only: [:edit, :update]

  def show
	  @booknew = Book.new
	  @book = Book.find(params[:id])
	  @user = User.find(@book.user_id)
	  @post_comments = @book.post_comments
	  @post_comment = PostComment.new
  end

  def index
	  @books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
	  @user = current_user
	  @book = Book.new
  end

  def create
	  @book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
	  @book.user_id = current_user.id
	  if @book.save #入力されたデータをdbに保存する。
  		redirect_to book_path(@book), notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
		  @books = Book.all
		  @user = current_user
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	book = Book.find(params[:id])
  	book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end
  def correct_user
    book = Book.find(params[:id])
    if current_user != book.user
      redirect_to books_path
    end
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_newform.html.erb
<% if @book.errors.any? %>
    <div class="error_explanation">
      <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
      <ul>
      <% @book.errors.full_messages.each do |msg| %>
        <li>
        <%= msg %>
        </li>
      <% end %>
      </ul>
    </div>
<% end %>

<%= form_for(book) do |f| %>
	<div class="field row">
		<%= f.label :title %>
		<%= f.text_field :title, class: "col-xs-12 book_title" %>
	</div>

	<div class="field row">
		<%= f.label :body %> <!-- ここを変更 -->
		<%= f.text_area :body, class: "col-xs-12 book_body" %>
	</div>

	<div class="actions row">
		<%= f.submit class: "btn btn-primary col-xs-12" %>
	</div>
<% end %>

app/views/books/edit.html.erb
<div class="row">
<div class="col-md-6 col-md-offset-3">
<% if @book.errors.any? %>
    <div class="error_explanation">
      <h2><%= @book.errors.count %> errors prohibited this obj from being saved:</h2>
      <ul>

      <% @book.errors.full_messages.each do |msg| %>
        <li>
        <%= msg %>
        </li>
      <% end %>
      </ul>
    </div>
  <% end %>
<h1>Editing Book</h1>

<%= render "books/newform", book: @book %>
<%= link_to "Show", @book, class: "book_#{@book.id}" %>
<%= link_to "Back", books_path, class: "back" %>

</div>
<div class="col-md-3"></div>

</div>

app/views/books/index.html.erb
<div class="container">
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books index</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to(book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
						<td><%= link_to book.title, book, class: "book_#{book.id}" %></td>
						<td><%= book.body %></td>

				<% if user_signed_in? %>
					<% if book.favorited_by?(current_user) %>
						<td><%= link_to book.favorites.count, book_favorites_path(book.id), method: :delete, class: 'glyphicon glyphicon-heart aria-hidden="true' %></td>
					<% else %>
						<td><%= link_to book.favorites.count, book_favorites_path(book.id), method: :post, class: 'glyphicon glyphicon-heart-empty aria-hidden="true' %></td>
					<% end %>
				<% else %>
						<td><span>お気に入り数: </span><%= book.favorites.count %></td>
				<% end %>
				<% if user_signed_in? %>
						<% if @book.post_commented_by?(current_user) %> <!-- ログインしているユーザーがコメントしたかどうかで分岐 -->
							<td><span>コメント数: </span><%=book.post_comments.count %></td>
						<% else %>
							<td><span>コメント数: </span><%=book.post_comments.count %></td>
						<% end %>
						<% else %>
							<td><span>コメント数: </span><%= book.post_comments.count %></td>
				<% end %>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->
	</div>
</div>
</div>

app/views/books/show.html.erb
<div class="container">
	<div class="row">
	<div class="col-xs-3">
	<h2>User info</h2>
		<%= render 'users/profile', user: @user%>


	<h2>New book</h2>
		<%= render 'books/newform', book: @booknew %>
	</div>
<!--book detail　本の詳細画面 -->
	<div class="col-xs-9">
		<h2>Book detail</h2>

		<table class="table">
				<tr>
					<td>
						<%= link_to (@book.user) do %>
						<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
						<%= @book.user.name %>
						<% end %>
					</td>

					<td><%= link_to @book.title, @book %></td>
					<td><%= @book.body %></td>

					<% if user_signed_in? %>
						<% if @book.favorited_by?(current_user) %>
							<td><%= link_to @book.favorites.count, book_favorites_path(@book.id), method: :delete, class: 'glyphicon glyphicon-heart aria-hidden="true' %></td>
						<% else %>
							<td><%= link_to @book.favorites.count, book_favorites_path(@book.id), method: :post, class: 'glyphicon glyphicon-heart-empty aria-hidden="true' %></td>
						<% end %>
					<% end %>
			</td>

					<% if user_signed_in? %>
						<% if @book.post_commented_by?(current_user) %> <!-- ログインしているユーザーがコメントしたかどうかで分岐 -->
							<td><span>コメント数: </span><%= @book.post_comments.count %></td>
						<% else %>
							<td><span>コメント数: </span><%= @book.post_comments.count %></td>
						<% end %>
						<% else %>
							<td><span>コメント数: </span><%= book.post_comments.count %></td>
					<% end %>

					<% if @user.id == current_user.id %><!--idが入らないといけないのに。省略されテイル？@book.id -->
						<td><%= link_to "Edit",edit_book_path(@book), class: "btn-sm btn-success edit_book_#{@book.id}" %></td>
						<td><%= link_to "Destroy",@book, method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@book.id}" %></td>
				 	<% end %>
				</tr>
			</table>



<h3>コメント一覧</h3>
<% @post_comments.each do |c| %>
		<table class="table">
			<tr>
				<td>
					<%= link_to (@book.user) do %>
					<%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-mini.jpg") %><br>
					<%= @book.user.name %>
					<% end %>
				</td>
				<td>
					<%= c.comment %>
				</td>
				<% if @user.id == current_user.id %><!--idが入らないといけないのに。省略されテイル？@book.id -->
						<td><%= link_to "Destroy",book_post_comment_path(c.book_id,c.id), method: :delete, data: {confirm: "本当に削除してもよろしいですか？"}, class: "btn-sm btn-danger destroy_book_#{@post_comment.id}" %></td>
				<% end %>
			</tr>
		</table>
<% end %>

	<%= form_for [@book, @post_comment] do |f| %>
		<div class="row">
			<div class="col-sm-12">
				<%= f.text_area :comment, rows:'5', class: "form-control",placeholder: "コメントをここに" %>
			</div>
		</div>
		<%= f.submit "送信", class: "btn btn-lg btn-base-1 mt-20 pull-right" %>
	<% end %>
		</div>
	</div>
</div>